insert into tb_armazem (id, descricao, nome) values (null, 'Armazem grande', 'Armazem 1');
insert into tb_setor (id, armazem_id, nome, tipo) values (null, 1, 'Setor A', 0);
insert into tb_representante (id, armazem_id, nome) values (null, 1, 'José Filho');
insert into tb_produto (id, conservacao, nome, volume_uni) values (null, 0, 'Carne', 70.0);
insert into tb_lote (id, data_fabricacao, data_validade, produto_id, quantidade_atual, quantidade_inicial, temperatura_atual, temperatura_minima) values (null, '2018-05-07T15:20:45.765Z', '2022-05-07T15:20:45.765Z', 1, 20, 10, 5.0, 7.0);
insert into tb_estoque (id, data, representante_id, setor_id) values (null,'2021-12-07T05:33:00Z' , 1, 1);
insert into tb_estoque_lotes (registro_de_estoques_id, lotes_id) values (1, 1);
insert into tb_vendedor (id, nome) values (null, 'João Primo');
insert into tb_anuncio (id, descricao, lote_id, preco, titulo, vendedor_id) values (null, 'Carne de primeira', 1, 100.00, 'Alcatra', 1);
insert into tb_comprador (id, carrinho_id, nome) values (null, null, 'Maria Green');
insert into tb_carrinho (id, compra_id, comprador_id) values (null, null, 1);
update tb_comprador set carrinho_id = 1 where id = 1;
insert into tb_carrinho_anuncio (id, anuncio_id, carrinho_id, quantidade) values (null, 1, 1, 3);
--insert into tb_compra (id, carrinho_id, data) values (null, 1, '2018-10-22T17:45:45.765Z');